// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_snapshot.proto

package gravity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSnapshotRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSnapshotRequest) Reset()         { *m = GetSnapshotRequest{} }
func (m *GetSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotRequest) ProtoMessage()    {}
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dabcf68fbf5d8713, []int{0}
}

func (m *GetSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotRequest.Unmarshal(m, b)
}
func (m *GetSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *GetSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotRequest.Merge(m, src)
}
func (m *GetSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotRequest.Size(m)
}
func (m *GetSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotRequest proto.InternalMessageInfo

type SnapshotPacket struct {
	Sequence             uint64           `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Entries              []*SnapshotEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SnapshotPacket) Reset()         { *m = SnapshotPacket{} }
func (m *SnapshotPacket) String() string { return proto.CompactTextString(m) }
func (*SnapshotPacket) ProtoMessage()    {}
func (*SnapshotPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_dabcf68fbf5d8713, []int{1}
}

func (m *SnapshotPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotPacket.Unmarshal(m, b)
}
func (m *SnapshotPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotPacket.Marshal(b, m, deterministic)
}
func (m *SnapshotPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotPacket.Merge(m, src)
}
func (m *SnapshotPacket) XXX_Size() int {
	return xxx_messageInfo_SnapshotPacket.Size(m)
}
func (m *SnapshotPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotPacket proto.InternalMessageInfo

func (m *SnapshotPacket) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *SnapshotPacket) GetEntries() []*SnapshotEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type SnapshotEntry struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotEntry) Reset()         { *m = SnapshotEntry{} }
func (m *SnapshotEntry) String() string { return proto.CompactTextString(m) }
func (*SnapshotEntry) ProtoMessage()    {}
func (*SnapshotEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_dabcf68fbf5d8713, []int{2}
}

func (m *SnapshotEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotEntry.Unmarshal(m, b)
}
func (m *SnapshotEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotEntry.Marshal(b, m, deterministic)
}
func (m *SnapshotEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotEntry.Merge(m, src)
}
func (m *SnapshotEntry) XXX_Size() int {
	return xxx_messageInfo_SnapshotEntry.Size(m)
}
func (m *SnapshotEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotEntry proto.InternalMessageInfo

func (m *SnapshotEntry) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *SnapshotEntry) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSnapshotRequest)(nil), "gravity.GetSnapshotRequest")
	proto.RegisterType((*SnapshotPacket)(nil), "gravity.SnapshotPacket")
	proto.RegisterType((*SnapshotEntry)(nil), "gravity.SnapshotEntry")
}

func init() { proto.RegisterFile("data_snapshot.proto", fileDescriptor_dabcf68fbf5d8713) }

var fileDescriptor_dabcf68fbf5d8713 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x49, 0x2c, 0x49,
	0x8c, 0x2f, 0xce, 0x4b, 0x2c, 0x28, 0xce, 0xc8, 0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x4f, 0x2f, 0x4a, 0x2c, 0xcb, 0x2c, 0xa9, 0x54, 0x12, 0xe1, 0x12, 0x72, 0x4f, 0x2d, 0x09,
	0x86, 0xca, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0xc5, 0x71, 0xf1, 0xc1, 0x84, 0x02,
	0x12, 0x93, 0xb3, 0x53, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x8a, 0x41, 0x92, 0x79, 0xc9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x70, 0xbe, 0x90, 0x01, 0x17, 0x7b, 0x6a, 0x5e, 0x49, 0x51,
	0x66, 0x6a, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x98, 0x1e, 0xd4, 0x78, 0x3d, 0x98,
	0x29, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x30, 0x65, 0x4a, 0x96, 0x5c, 0xbc, 0x28, 0x32, 0x42,
	0x22, 0x5c, 0xac, 0x25, 0x89, 0x49, 0x39, 0x10, 0xb3, 0x39, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e,
	0x16, 0x90, 0xe3, 0x25, 0x98, 0xc0, 0x82, 0x60, 0xb6, 0x51, 0x38, 0x17, 0x8f, 0x4b, 0x62, 0x49,
	0x22, 0x4c, 0xbb, 0x90, 0x3b, 0x17, 0x37, 0x92, 0x07, 0x84, 0xa4, 0xe1, 0x56, 0x63, 0x7a, 0x4b,
	0x4a, 0x1c, 0xc3, 0x5d, 0x10, 0xdf, 0x29, 0x31, 0x18, 0x30, 0x26, 0xb1, 0x81, 0x43, 0xc6, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xca, 0x8f, 0xd0, 0x30, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataSnapshotClient is the client API for DataSnapshot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataSnapshotClient interface {
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (DataSnapshot_GetSnapshotClient, error)
}

type dataSnapshotClient struct {
	cc *grpc.ClientConn
}

func NewDataSnapshotClient(cc *grpc.ClientConn) DataSnapshotClient {
	return &dataSnapshotClient{cc}
}

func (c *dataSnapshotClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (DataSnapshot_GetSnapshotClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataSnapshot_serviceDesc.Streams[0], "/gravity.DataSnapshot/GetSnapshot", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataSnapshotGetSnapshotClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataSnapshot_GetSnapshotClient interface {
	Recv() (*SnapshotPacket, error)
	grpc.ClientStream
}

type dataSnapshotGetSnapshotClient struct {
	grpc.ClientStream
}

func (x *dataSnapshotGetSnapshotClient) Recv() (*SnapshotPacket, error) {
	m := new(SnapshotPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataSnapshotServer is the server API for DataSnapshot service.
type DataSnapshotServer interface {
	GetSnapshot(*GetSnapshotRequest, DataSnapshot_GetSnapshotServer) error
}

// UnimplementedDataSnapshotServer can be embedded to have forward compatible implementations.
type UnimplementedDataSnapshotServer struct {
}

func (*UnimplementedDataSnapshotServer) GetSnapshot(req *GetSnapshotRequest, srv DataSnapshot_GetSnapshotServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}

func RegisterDataSnapshotServer(s *grpc.Server, srv DataSnapshotServer) {
	s.RegisterService(&_DataSnapshot_serviceDesc, srv)
}

func _DataSnapshot_GetSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSnapshotServer).GetSnapshot(m, &dataSnapshotGetSnapshotServer{stream})
}

type DataSnapshot_GetSnapshotServer interface {
	Send(*SnapshotPacket) error
	grpc.ServerStream
}

type dataSnapshotGetSnapshotServer struct {
	grpc.ServerStream
}

func (x *dataSnapshotGetSnapshotServer) Send(m *SnapshotPacket) error {
	return x.ServerStream.SendMsg(m)
}

var _DataSnapshot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.DataSnapshot",
	HandlerType: (*DataSnapshotServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSnapshot",
			Handler:       _DataSnapshot_GetSnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data_snapshot.proto",
}
